### ISSUE TITLE
Interactions class should check for implicit data and give warning/error

### ISSUE THREAD

**Issue by peterskipper** [ShopRunner/collie_recs#7]
Passing in a dataset to the `Interactions` class with positive and negative interactions can fail downstream when you try to evaluate your model with `auc`, if your split puts only negative interactions for a user into the validation set. Assuming a user wants an implicit interactions dataset (i.e. only positive interactions) can we throw an error when the Interactions dataset is formed to let them know?

Thanks for all the hard work on this, love the repo ❤️

**Comment by nathancooperjones** [comment]
In https://github.com/ShopRunner/collie_recs/pull/9, I added code to the ``Interactions`` class that checks if ``0``s are in an ``Interactions`` object during instantiation and, if so, removes those rows. That should hopefully fix this issue once merged in. 

Cheers!
